# Generated by Django 5.2.5 on 2025-11-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='board',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
